editing forms
gmcglinn/Projects_CPS485 pull request #18
Opened 2021-04-04 23:59 UTC by carrasqa1

> re-working the forms, fixing the css to reflect the current site.
> going to create a page that will allow the user to select their specific form

2021-04-05 02:26 UTC, carrasqa1 commented
- really having trouble getting the CSS to be consistent, does anyone have any ideas to get that to work?

2021-04-06 18:22 UTC, varlack1021 approved these changes

2021-04-06 18:23 UTC, varlack1021 requested changes
You have some merge conflicts here

2021-04-07 01:22 UTC, varlack1021 approved these changes

2021-04-07 01:22 UTC, merged